name: Shell commands

m: [push]

jobs:
  run-shell-command:
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multiline command
        run: |
          node -v
          npm -v
