name: Shell commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: pwd and ls -la
        run: |
          pwd
          ls -la
          ls -lrt
  run-windows-commands:
    runs-on: windows-latest
    needs: ["run-shell-command"]
    steps:
      - name: Directory powershell
        run: Get-Location
      - name: Directory bash
        run: pwd
        shell: bash
