name: Shell commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multiline command
        run: |
          node -v
          npm -v
      - name: Pyhton command
        run: |
          python --version
          import platform
          print(platform.processor())
