name: Checkout code and perform operations

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List files before checkout
        run: |
          pwd
          ls -la
      - name: checkout code
        uses: actions/checkout@v2
      - name: List files after checkout
        run: |
          pwd
          ls -la
