name: Shell commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: pwd and ls -la
        run: |
          pwd
          ls -la
          ls -lrt
      - name: multiline command
        run: |
          node -v
          npm -v
      - name: Pyhton command
        run: |
          import platform
          print(platform.processor())
        shell: python
